#ifndef OPTIONSDEF_H
#define OPTIONSDEF_H

#define RSASS_PRECISION 0
#define RSASS_OUTPUT_STYLE 1
#define RSASS_SOURCE_COMMENTS 2
#define RSASS_SOURCE_MAP_EMBED 3
#define RSASS_SOURCE_MAP_CONTENTS 4
#define RSASS_OMIT_SOURCE_MAP_URL 5
#define RSASS_INDENTED_SYNTAX 6
#define RSASS_LINEFEED 7
#define RSASS_OUTPUT_PATH 8
#define RSASS_INCLUDE_PATH 9
#define RSASS_SOURCE_MAP_FILE 10
#define RSASS_SOURCE_MAP_ROOT 11
#define RSASS_INDENT 12

#endif
